# Generated by Django 4.2.6 on 2023-12-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scouting", "0002_rename_first_name_player_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="slug",
            field=models.SlugField(default="", max_length=255),
        ),
    ]
