# Generated by Django 4.2.6 on 2023-12-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scouting", "0003_player_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
